import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/web/navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/web/footer";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Better-Auth",
  description: "Generated by React 19 with better-auth",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased font-sans", geistSans.variable, geistMono.variable,  inter.variable)}
    >

      
      <body className = "w-full bg-dark text-black">

      <Navbar/>
        
        
      {children}


      <Footer/>
      
      
      
      </body>
    </html>
  );
}
